from django.urls import path, re_path
from .views import general, anonimo, academico, alumno
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('%sadmin/' % settings.PATH_PREFIX, admin.site.urls, name="admin"),
    path('%slogin/' % settings.PATH_PREFIX, anonimo.iniciar_sesion, name="login"),
    path('%sacademicos/registro/' % settings.PATH_PREFIX, anonimo.registrar_academico, name="registrar_academico"),
    path('%salumnos/registro/' % settings.PATH_PREFIX, anonimo.registrar_alumno, name="registrar_alumno"),
    path('%s' % settings.PATH_PREFIX, general.inicio, name="inicio"),
    path('%slogout/' % settings.PATH_PREFIX, general.cerrar_sesion, name="logout"),
    path('%sayuda/' % settings.PATH_PREFIX, general.ver_ayuda, name="ayuda"),
    path('%scursos-<int:pk_curso>/' % settings.PATH_PREFIX, general.ver_curso, name="curso_detalle"),
    path('%scursos-<int:pk_curso>/practicas/' % settings.PATH_PREFIX, general.ver_listado_practicas, name="listado_practicas"),
    path('%scursos-<int:pk_curso>/examenes/' % settings.PATH_PREFIX, general.ver_listado_examenes, name="listado_examenes"),
    path('%scursos-<int:pk_curso>/integrantes/' % settings.PATH_PREFIX, general.ver_listado_integrantes_curso,
         name="listado_integrantes_curso"),
    path('%sperfil-academico/editar/' % settings.PATH_PREFIX, academico.editar_perfil, name="editar_perfil_academico"),
    path('%stemas/registro/' % settings.PATH_PREFIX, academico.agregar_tema, name="agregar_tema"),
    path('%sejercicios/listado/' % settings.PATH_PREFIX, academico.ver_listado_ejercicios, name="listado_ejercicios"),
    path('%sejercicios/registro/' % settings.PATH_PREFIX, academico.agregar_ejercicio, name="agregar_ejercicio"),
    re_path(r'^%sejercicios/(?P<id_ejercicio>[0-9A-Fa-f-]+)/editar$' % settings.PATH_PREFIX, academico.editar_ejercicio, name="ejercicio_editar"),
    re_path(r'^%sejercicios/(?P<id_ejercicio>[0-9A-Fa-f-]+)/evaluar$' % settings.PATH_PREFIX, academico.evaluar_ejercicio, name="ejercicio_evaluar"),
    re_path(r'^%sejercicios/(?P<id_ejercicio>[0-9A-Fa-f-]+)/detalle$' % settings.PATH_PREFIX, academico.ver_detalle_ejercicio, name="ejercicio_detalle"),
    path('%scursos/registro/' % settings.PATH_PREFIX, academico.agregar_curso, name="agregar_curso"),
    path('%scursos/listado/' % settings.PATH_PREFIX, academico.ver_listado_cursos, name="listado_cursos"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/editar$' % settings.PATH_PREFIX, academico.editar_curso, name="curso_editar"),
    path('%scursos-<int:pk_curso>/practicas/registro/' % settings.PATH_PREFIX, academico.agregar_practica, name="agregar_practica"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/practicas-(?P<pk_practica>\d+)/editar$' % settings.PATH_PREFIX, academico.editar_practica,
            name="editar_practica"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/practicas-(?P<pk_practica>\d+)/eliminar$' % settings.PATH_PREFIX, academico.eliminar_practica,
            name="eliminar_practica"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/practicas-(?P<pk_practica>\d+)/puntajes$' % settings.PATH_PREFIX, academico.ver_puntajes_practica,
            name="ver_puntajes_practica"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/practicas-(?P<pk_practica>\d+)/puntajes/respuestas-(?P<pk_respuesta>\d+)$' % settings.PATH_PREFIX,
            academico.ver_respuesta_ejercicio_practica, name="detalle_respuesta_practica"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes/registro$' % settings.PATH_PREFIX, academico.agregar_examen, name="agregar_examen"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes-(?P<pk_examen>\d+)/editar$' % settings.PATH_PREFIX, academico.editar_examen,
            name="editar_examen"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes-(?P<pk_examen>\d+)/eliminar$' % settings.PATH_PREFIX, academico.eliminar_examen,
            name="eliminar_examen"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes-(?P<pk_examen>\d+)/puntajes$' % settings.PATH_PREFIX, academico.ver_puntajes_examen,
            name="ver_puntajes_examen"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes-(?P<pk_examen>\d+)/activar$' % settings.PATH_PREFIX, academico.activar_examen,
            name="activar_examen"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes-(?P<pk_examen>\d+)/administrar$' % settings.PATH_PREFIX, academico.administrar_examen,
            name="administrar_examen"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes-(?P<pk_examen>\d+)/concluir$' % settings.PATH_PREFIX, academico.concluir_examen,
            name="concluir_examen"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes-(?P<pk_examen>\d+)/puntajes/respuestas-(?P<pk_respuesta>\d+)$' % settings.PATH_PREFIX,
            academico.ver_respuesta_ejercicio_examen,
            name="detalle_respuesta_examen"),
    re_path(r'^%salumnos/(?P<pk_estudiante>[0-9A-Fa-f-]+)/cambiarps$' % settings.PATH_PREFIX, academico.cambiar_pass,
            name="cambiar_ps"),
    re_path(r'^%scursos/(?P<pk_curso>\d+)/puntajes-generales$' % settings.PATH_PREFIX, academico.ver_puntajes_generales,
            name="ver_puntajes_generales"),
    path('%sperfil-alumno/editar/' % settings.PATH_PREFIX, alumno.editar_perfil, name="editar_perfil_alumno"),
    path('%scursos/inscripcion/' % settings.PATH_PREFIX, alumno.inscribir_curso, name="inscribir_curso"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/practicas-(?P<pk_practica>\d+)$' % settings.PATH_PREFIX, alumno.ver_detalle_practica,
            name="practica_detalle"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/practicas-(?P<pk_practica>\d+)/ejercicios-(?P<pk_ejercicio>[0-9A-Fa-f-]+)$' % settings.PATH_PREFIX,
            alumno.resolver_ejercicio_practica, name="resolver_ejercicio_practica"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes-(?P<pk_examen>\d+)$' % settings.PATH_PREFIX, alumno.ver_detalle_examen,
            name="examen_detalle"),
    re_path(r'^%scursos-(?P<pk_curso>\d+)/examenes-(?P<pk_examen>\d+)/ejercicios-(?P<pk_ejercicio>[0-9A-Fa-f-]+)$' % settings.PATH_PREFIX,
            alumno.resolver_ejercicio_examen, name="resolver_ejercicio_examen"),
]