# Generated by Django 2.0 on 2018-10-10 00:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import evaluador_codigo.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False, verbose_name='Estudiante')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Académico')),
                ('img_profile', models.ImageField(blank=True, max_length=500, null=True, storage=evaluador_codigo.models.OverwriteStorage(), upload_to=evaluador_codigo.models.get_upload_img_profile, verbose_name='Imagen de perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Académico',
                'verbose_name_plural': 'Academicos',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=9, unique=True, verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(max_length=5, verbose_name='NRC')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('bloque', models.CharField(max_length=2, verbose_name='Bloque')),
                ('seccion', models.CharField(max_length=2, verbose_name='Sección')),
                ('codigo_inscripcion', models.CharField(max_length=10, verbose_name='Código de inscripción')),
                ('academico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.Academico')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['exp_educativa'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('publico', models.BooleanField(default=False, verbose_name='Público')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('entrada', models.TextField(blank=True, null=True, verbose_name='Entrada')),
                ('salida', models.TextField(blank=True, null=True, verbose_name='Salida')),
                ('ejemplo_entrada', models.TextField(verbose_name='Ejemplo entrada')),
                ('ejemplo_salida', models.TextField(verbose_name='Ejemplo salida')),
                ('casos_prueba', models.FileField(max_length=500, storage=evaluador_codigo.models.OverwriteStorage(), upload_to=evaluador_codigo.models.get_upload_casos_prueba, verbose_name='Casos de prueba')),
                ('archivo_apoyo', models.FileField(blank=True, max_length=500, null=True, storage=evaluador_codigo.models.OverwriteStorage(), upload_to=evaluador_codigo.models.get_upload_archivo_apoyo, verbose_name='Archivo de apoyo')),
                ('academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.Academico')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EjerciciosExamenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.Ejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicios de práctica',
                'verbose_name_plural': 'Ejercicios de prácticas',
            },
        ),
        migrations.CreateModel(
            name='EjerciciosPracticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.Ejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicios de práctica',
                'verbose_name_plural': 'Ejercicios de prácticas',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Examen')),
                ('estado', models.CharField(default='por iniciar', max_length=11, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_termino', models.DateTimeField(blank=True, null=True, verbose_name='Fecha término')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='evaluador_codigo.Curso')),
                ('ejercicios', models.ManyToManyField(through='evaluador_codigo.EjerciciosExamenes', to='evaluador_codigo.Ejercicio')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaEducativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_educativa', models.CharField(max_length=50, unique=True, verbose_name='Experiencia educativa')),
            ],
            options={
                'verbose_name': 'Experiencia educativa',
                'verbose_name_plural': 'Experiencias educativas',
                'ordering': ['exp_educativa'],
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenciatura', models.CharField(max_length=50, unique=True, verbose_name='Licenciatura')),
            ],
            options={
                'verbose_name': 'Licenciatura',
                'verbose_name_plural': 'Licenciaturas',
                'ordering': ['licenciatura'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, unique=True, verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['periodo'],
            },
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('inicio', models.DateTimeField(verbose_name='Fecha inicio')),
                ('termino', models.DateTimeField(verbose_name='Fecha término')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='evaluador_codigo.Curso')),
                ('ejercicios', models.ManyToManyField(through='evaluador_codigo.EjerciciosPracticas', to='evaluador_codigo.Ejercicio')),
            ],
            options={
                'verbose_name': 'Práctica',
                'verbose_name_plural': 'Prácticas',
            },
        ),
        migrations.CreateModel(
            name='RespuestasExamenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.IntegerField(default=0, verbose_name='Puntaje')),
                ('archivo_respuesta', models.FileField(max_length=500, storage=evaluador_codigo.models.OverwriteStorage(), upload_to=evaluador_codigo.models.get_upload_respuesta_examen, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'java', 'prolog', 'cpp', 'c', 'lisp', 'zip'])], verbose_name='Respuesta')),
                ('archivo_respuesta_temporal', models.FileField(blank=True, max_length=500, null=True, storage=evaluador_codigo.models.OverwriteStorage(), upload_to=evaluador_codigo.models.get_upload_respuesta_temporal_examen, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'java', 'prolog', 'cpp', 'c', 'lisp', 'zip'])], verbose_name='Respuesta temporal')),
                ('fecha_enviado', models.DateTimeField(auto_now=True, verbose_name='Fecha enviado')),
                ('error', models.CharField(max_length=100, null=True, verbose_name='Error')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_examen', to='evaluador_codigo.Alumno')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.EjerciciosExamenes')),
            ],
            options={
                'verbose_name': 'Respuesta de ejercicio',
                'verbose_name_plural': 'Respuesta de ejercicio',
            },
        ),
        migrations.CreateModel(
            name='RespuestasPracticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.IntegerField(default=0, verbose_name='Puntaje')),
                ('archivo_respuesta', models.FileField(max_length=500, storage=evaluador_codigo.models.OverwriteStorage(), upload_to=evaluador_codigo.models.get_upload_respuesta_practica, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'java', 'prolog', 'cpp', 'c', 'lisp', 'zip'])], verbose_name='Respuesta')),
                ('archivo_respuesta_temporal', models.FileField(blank=True, max_length=500, null=True, storage=evaluador_codigo.models.OverwriteStorage(), upload_to=evaluador_codigo.models.get_upload_respuesta_temporal_practica, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'java', 'prolog', 'cpp', 'c', 'lisp', 'zip'])], verbose_name='Respuesta temporal')),
                ('fecha_enviado', models.DateTimeField(auto_now=True, verbose_name='Fecha enviado')),
                ('error', models.CharField(max_length=100, null=True, verbose_name='Error')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_practica', to='evaluador_codigo.Alumno')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.EjerciciosPracticas')),
            ],
            options={
                'verbose_name': 'Respuesta de ejercicio',
                'verbose_name_plural': 'Respuesta de ejercicio',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=250, unique=True, verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.AddField(
            model_name='ejerciciospracticas',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.Practica'),
        ),
        migrations.AddField(
            model_name='ejerciciosexamenes',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.Examen'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='experiencias_educativas',
            field=models.ManyToManyField(to='evaluador_codigo.ExperienciaEducativa'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='temas',
            field=models.ManyToManyField(to='evaluador_codigo.Tema'),
        ),
        migrations.AddField(
            model_name='curso',
            name='exp_educativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='evaluador_codigo.ExperienciaEducativa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='licenciatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='evaluador_codigo.Licenciatura'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.Periodo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(related_name='alumnos', to='evaluador_codigo.Curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='licenciatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluador_codigo.Licenciatura'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='respuestas_examenes',
            field=models.ManyToManyField(through='evaluador_codigo.RespuestasExamenes', to='evaluador_codigo.EjerciciosExamenes'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='respuestas_practicas',
            field=models.ManyToManyField(through='evaluador_codigo.RespuestasPracticas', to='evaluador_codigo.EjerciciosPracticas'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academico',
            name='licenciaturas',
            field=models.ManyToManyField(to='evaluador_codigo.Licenciatura'),
        ),
        migrations.AddField(
            model_name='academico',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaspracticas',
            unique_together={('ejercicio', 'alumno')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestasexamenes',
            unique_together={('ejercicio', 'alumno')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nrc', 'periodo')},
        ),
    ]
