# Generated by Django 2.0.4 on 2019-02-09 20:53

from django.db import migrations, models
import evaluador_codigo.models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_codigo', '0002_auto_20181019_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, max_length=200, null=True, storage=evaluador_codigo.models.OverwriteStorage(), upload_to=evaluador_codigo.models.get_upload_img_profile, verbose_name='Imagen de perfil'),
        ),
    ]
