# Generated by Django 4.2.11 on 2024-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_codigo', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('intentos', models.PositiveBigIntegerField()),
                ('fecha_ultimo_intento', models.DateTimeField()),
            ],
        ),
    ]
