# Generated by Django 4.2.11 on 2024-08-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_codigo', '0005_intentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioEvaluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
