# Generated by Django 2.0.4 on 2018-10-19 08:57

from django.db import migrations, models
import evaluador_codigo.models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador_codigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=evaluador_codigo.models.OverwriteStorage(), upload_to=evaluador_codigo.models.get_upload_img_profile, verbose_name='Imagen de perfil'),
        ),
    ]
